// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLxYszHoAj5GWoXVg5-jkY3Qnh_RLytA0',
    appId: '1:880654207788:web:52208dccb7c5a6272e7a89',
    messagingSenderId: '880654207788',
    projectId: 'toucan-8676b',
    authDomain: 'toucan-8676b.firebaseapp.com',
    storageBucket: 'toucan-8676b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcPz3qTGBE_kwvWeqJ5Z7od9hnNUel_BY',
    appId: '1:880654207788:android:346e576fa96747b32e7a89',
    messagingSenderId: '880654207788',
    projectId: 'toucan-8676b',
    storageBucket: 'toucan-8676b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Blezd_avQNeo8N-bGoDBK7fz5UFgADs',
    appId: '1:880654207788:ios:f09d3103d30c0ef72e7a89',
    messagingSenderId: '880654207788',
    projectId: 'toucan-8676b',
    storageBucket: 'toucan-8676b.appspot.com',
    iosClientId: '880654207788-28pma108d0n3al050ak94apa4oukmicb.apps.googleusercontent.com',
    iosBundleId: 'toucan.com.toucan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Blezd_avQNeo8N-bGoDBK7fz5UFgADs',
    appId: '1:880654207788:ios:f09d3103d30c0ef72e7a89',
    messagingSenderId: '880654207788',
    projectId: 'toucan-8676b',
    storageBucket: 'toucan-8676b.appspot.com',
    iosClientId: '880654207788-28pma108d0n3al050ak94apa4oukmicb.apps.googleusercontent.com',
    iosBundleId: 'toucan.com.toucan',
  );
}
